services:
  - type: web
    name: pct-class-scheduling
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        value: buwyFvp2ejdwjgoxsbcw-mysql.services.clever-cloud.com
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: buwyFvp2ejdwjgoxsbcw
      - key: DB_USER
        value: uux4xvgrm7xvbwe6a
      - key: DB_PASS
        value: itYX61CE0bZ6ea4mUKE6
      - key: APP_URL
        value: $RENDER_EXTERNAL_URL
      - key: APP_ENV
        value: production
