services:
  - type: web
    name: pct-class-scheduling
    runtime: php
    plan: standard
    buildCommand: bash ./build.sh
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: pct-class-scheduling-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: pct-class-scheduling-db
          property: port
      - key: DB_NAME
        value: class_scheduling
      - key: DB_USER
        fromDatabase:
          name: pct-class-scheduling-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: pct-class-scheduling-db
          property: password
      - key: APP_URL
        value: $RENDER_EXTERNAL_URL
      - key: APP_ENV
        value: production

databases:
  - name: pct-class-scheduling-db
    databaseName: class_scheduling
    user: pct_user
    plan: free
