-- Seed data for classrooms and instructors
-- Generated on 2026-04-03 from local database class_scheduling
START TRANSACTION;

-- Classrooms
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('101', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('102', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('103', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('104', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('105', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('106', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('107', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('108', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('109', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('110', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('201', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('202', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('203', 3, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('204', 30, 'Main Building', 'comlab', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('205', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('206', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('207', 30, 'Main Building', 'comlab', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('208', 30, 'Main Building', 'comlab', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('209', 30, 'Main Building', 'comlab', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('210', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('301', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('302', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('303', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('304', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('305', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('306', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('307', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('308', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('309', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('310', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('401', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('402', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('403', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('404', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('405', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('406', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('407', 30, 'Main Building', 'conference', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('408', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('409', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('410', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('501', 30, 'Main Building', 'laboratory', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('502', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('503', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('504', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('505', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('506', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('507', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('508', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('509', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('510', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('601', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('602', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('603', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('604', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('605', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('606', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('607', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('608', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('609', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('610', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);
INSERT INTO classrooms (room_number, capacity, building, room_type, status) VALUES ('701', 30, 'Main Building', 'lecture', 'active') ON DUPLICATE KEY UPDATE capacity=VALUES(capacity), building=VALUES(building), room_type=VALUES(room_type), status=VALUES(status);

-- Instructors
INSERT INTO users (username, password, email, role, first_name, last_name) VALUES ('EdwinAmaga', '$2y$10$zLhgEjI7ErlqJPJDuydyV.8J1IveMzRT2xyDVwOSaMEVxdDA4pgya', 'Edwin.Amaga@pctdavao.edu.ph', 'instructor', 'Edwin', 'Amaga') ON DUPLICATE KEY UPDATE email=VALUES(email), role=VALUES(role), first_name=VALUES(first_name), last_name=VALUES(last_name);
INSERT INTO users (username, password, email, role, first_name, last_name) VALUES ('JeffreyOñas', '$2y$10$Al7bV5c9Tmpu0k.UiNwhPeoTCVGtTE0n5bSMY/5ecJlp/1YybC63K', 'Jeffrey.Onas@pctdavao.edu.ph', 'instructor', 'Jeffrey', 'Oñas') ON DUPLICATE KEY UPDATE email=VALUES(email), role=VALUES(role), first_name=VALUES(first_name), last_name=VALUES(last_name);
INSERT INTO users (username, password, email, role, first_name, last_name) VALUES ('ChristianGregorio', '$2y$10$b9.xHapnDaCxFT4E0uiWw.FY279Un8YSLBUqgdRh8.YMlqXK8dnw6', 'Christian.Gregorio@pctdavao.edu.ph', 'instructor', 'Christian', 'Gregorio') ON DUPLICATE KEY UPDATE email=VALUES(email), role=VALUES(role), first_name=VALUES(first_name), last_name=VALUES(last_name);
INSERT INTO users (username, password, email, role, first_name, last_name) VALUES ('JohnRayJosol', '$2y$10$GERFil6m2Up6nZaUkOuGNu/RnEgRUvGWZumUjVM2t.G4F2tte6hP6', 'JohnRay.Josol@pctdavao.edu.ph', 'instructor', 'John Ray', 'Josol') ON DUPLICATE KEY UPDATE email=VALUES(email), role=VALUES(role), first_name=VALUES(first_name), last_name=VALUES(last_name);
INSERT INTO users (username, password, email, role, first_name, last_name) VALUES ('MarissaAntig', '$2y$10$nnkbTcgSLo.4/d3cpfX.aOfiK6hA55wT36hXHn7UzzUJRf0ZKvMU.', 'Marissa.Antig@pctdavaoedu.ph', 'instructor', 'Marissa', 'Antig') ON DUPLICATE KEY UPDATE email=VALUES(email), role=VALUES(role), first_name=VALUES(first_name), last_name=VALUES(last_name);
INSERT INTO users (username, password, email, role, first_name, last_name) VALUES ('NelsonBonifacio', '$2y$10$h9tx01hsHZxu4yX11KUwcuLATd2hG8PvOWV56MG4J2rFIAc/XFc8C', 'Nelson.Bonifacio@pctdavao.edu.ph', 'instructor', 'Nelson', 'Bonifacio') ON DUPLICATE KEY UPDATE email=VALUES(email), role=VALUES(role), first_name=VALUES(first_name), last_name=VALUES(last_name);

COMMIT;
